services:
  db:
    image: postgres:16
    container_name: fp_db
    environment:
      POSTGRES_DB: finplan
      POSTGRES_USER: psqladmin
      POSTGRES_PASSWORD: qweasd123
    ports:
      - "5431:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data

  backend-prod:
    build:
      context: ./backend
      target: prod
    container_name: fp_back_prod
    ports:
      - "8080:8080"
    depends_on:
      - db
    profiles: [ "prod" ]

  frontend-prod:
    build:
      context: ./frontend
      target: prod
    container_name: fp_front_prod
    ports:
      - "80:80"
    depends_on:
      - backend-prod
    profiles: [ "prod" ]

  backend-dev:
    build:
      context: ./backend
      target: dev
    container_name: fp_back_dev
    volumes:
      - ./backend:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    profiles: [ "dev" ]

  frontend-dev:
    build:
      context: ./frontend
      target: dev
    container_name: fp_front_dev
    environment:
      - NODE_ENV=development
    ports:
      - "80:8080"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend-dev
    profiles: [ "dev" ]