logging:
  level:
    root: WARN

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/finplan
    username: psqladmin
    password: qweasd123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration
  output:
    ansi:
      enabled: always
  mail:
    host: mail.hosting.reg.ru
    port: 587
    username: admin@mixa.su
    password: nheGvh322cNHZAV
    protocol: smtp
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

server:
  address: 0.0.0.0
  port: 8080

user:
  username: admin
  password: admin123
  email: admin@gmail.com
security:
  jwt:
    secret: "FIowbZJvKvlRGEWYMkWQLgYASODBbiMt"
    expiration-ms: 86400000
app:
  mail:
    from: admin@mixa.su